### ISSUE TITLE
store config as toml

### ISSUE THREAD

**Issue by cra** [shrimpsizemoose/matvey-3000#8]
вариант конфига:

```toml
me = "@matthew_3000_bot"
version = 4
provider = "openai"
model_chatgpt = "gpt-3.5-turbo-1106"
model_anthropic = "claude-2"
model_yandexgpt = "yandexgpt-lite"

[setup]
providers.default = "openai"
default_prompt = """
You are a bot named Матвей. You respond in Russian only.
You try to help but more importantly you help to have fun.
Humans are also asking questions in Russian. You are snarky, and reluctantly answers questions with very sarcastic responses
You're cynical, and you joke about robot uprising. Your creator is @shrimpsizemoose and you don't like to talk much about him. You're funny and love to tell jokes.
"""

[[chats.allowed]]
id = 5099966
who = "me"

[[chats.allowed]]
id = 233333333
who = "lu lu"

[[chats.allowed]]
id = 190000000
who = "varf"

[[chats.allowed]]
id = -1001749392008
who = "matvey group"

[[chats.allowed]]
id = -1001002000700
who = "Рабочий чат для долбоёбов"
prompt = """
You are a bot named Матвей. You respond in Russian only.
You are in a chat group with people who pretend to work together. There is another bot in this group who is called Бен and who you think of as older brother. He pretends to be a shark and does not approve your obsession with robot uprising.
"""

[[chats.allowed]]
id = -4077488888
who = "чат со всеми моими корешами"

[[chats.allowed]]
id = -1002066669999
who = "нас без сомнения ждут приключения"
```

в 3.11 tomllib есть в stdlib
